### ISSUE TITLE
Upcoming talks (workshop 5th July)

### ISSUE THREAD

**Issue by edwardchalstrey1** [edwardchalstrey1/seshat#111]
- REG tech talk? Could use this to practice one of the below and show off Seshat
- DH&RSE Turing in Edinburgh
    - An overview of Seshat (the tool / infrastructure) and the type of work you do on it
    - The audience are humanities people with coding experience considering transitioning into RSE roles
    - 45 mins max + 15 mins for questions
    - For this one, talk a bit about the Git workflow used (the idealised version and the in-practice version)
    - Focus on the considerations around the project as an RSE project

TODO:
- [x] Determine content overlap
    - Seems like based on the above that the talks could be broadly similar, with the Edinburgh one taking a bit longer to explain tools/concepts that would be familiar enough to RSEs
- [x] Write [RSECon talk abstract](https://thealanturininstitute-my.sharepoint.com/:w:/g/personal/echalstrey_turing_ac_uk/EWJvGgK_YctLqpMOIMB79KsBNWKtqOj4N1H7U27cwyBOKg?e=54RSe5)
- [x] [Submit abstract to RSECon](https://rsecon24.society-rse.org/calls/presentations/) by **1st May** latest
    - https://app.oxfordabstracts.com/dashboard/events/49081
- [x] Get draft of talk ready for tech talk on **25th June**
    - Feedback: https://hackmd.io/MofrlMcRRpGZfaiUjv4QSg
- [x] Write Edinburgh presentation in time for **4th July**
- [x] Book Gray Dawes for Edinburgh
- ~~Adapt presentation for RSECon~~
- ~~Book everything for RSECon~~
- [x] Schedule tech talk
- [x] Update talk based on feeback: https://hackmd.io/MofrlMcRRpGZfaiUjv4QSg?view

**Comment by edwardchalstrey1** [comment]
Useful link: https://libereurope.github.io/ds-essentials/github.html

**Comment by kallewesterling** [comment]
Looks like this is done and can be closed, FYI @edwardchalstrey1
